In [ ]:
# Project root setup
import os
import sys
from pathlib import Path

ROOT = next((path for path in (Path.cwd(), *Path.cwd().parents) if (path / "src").is_dir()), None)
if ROOT is None:
    raise RuntimeError("Could not locate the project root containing src/.")
os.chdir(ROOT)
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

In [1]:
import numpy as np
from numpy import linalg as la
from time import perf_counter
import os
from joblib import Parallel, delayed

import itertools

from src.model import Nonneg_dagma, MetMulDagma, MetMulColide
import src.utils as utils

PATH = './results/tuning/'
PATH_SACHS = './datasets/sachs/'
SEED = 10
N_CPUS = os.cpu_count() // 2
np.random.seed(SEED)

DATASET = "SACHS"  # SYNTH, SACHS

In [2]:
def get_lamb_value(n_nodes, n_samples, times=1):
    return np.sqrt(np.log(n_nodes) / n_samples) * times 

def cartesian_product(hyperparams):
    """
    Generate all combinations of hyperparameters.
    """
    param_names = list(hyperparams.keys())
    param_values = list(hyperparams.values())    
    param_combinations = [dict(zip(param_names, values)) for values in itertools.product(*param_values)]
    
    return param_combinations

args2str = lambda arguments: ''.join([f'{key[:3]}={val} ' for key, val in arguments.items()])

def print_best(key, metrics, args_combs, agg_funct='mean', all_best=False):
    agg_metric = {key: getattr(np, agg_funct)(value, axis=0) for key, value in metrics.items()}
        
    best_value = np.min(agg_metric[key])
    best_idxs = np.where(agg_metric[key] == best_value)[0]

    if not all_best:
        best_idxs = [best_idxs[0]]

    print(f'Combination{"s" if all_best else ""} with best {key} (agg: {agg_funct}):')
    for idx in best_idxs:
        print(args_combs[idx])
        print(f'shd: {agg_metric["shd"][idx]:.2f} | err: {agg_metric["err"][idx]:.4f} |' +
              f'acyc: {agg_metric["acyc"][idx]:.6f} | time: {agg_metric["time"][idx]:.2f}')
        
    # idx = np.argmin(agg_metric[key])

    # print(f'Combination with best {key} (agg: {agg_funct}):')
    # print(args_combs[idx])
    # print(f'shd: {agg_metric["shd"][idx]:.2f} | err: {agg_metric["err"][idx]:.4f} |' +
    #       f'acyc: {agg_metric["acyc"][idx]:.6f} | time: {agg_metric["time"][idx]:.2f}')



def run_grid_search_tuning(g, data_p, args_combs, model_const, model_args, std_x, fix_lamb, thr, verb=False):
    # Create data
    if DATASET == "SACHS":
        W_true = np.load(PATH_SACHS + "sachs_A_matrix.npy")
        X = np.load(PATH_SACHS + "sachs_X.npy")
    else:
        W_true, _, X = utils.simulate_sem(**data_p)
        
    # X = X/np.linalg.norm(X, axis=1, keepdims=True) if std_x else X
    X = utils.standarize(X) if std_x else X
    norm_W_true = np.linalg.norm(W_true)
    W_true_bin = utils.to_bin(W_true, thr)
    M, N = X.shape

    fidelity = 1/data_p['n_samples']*la.norm(X - X @ W_true, 'fro')**2

    print(f'Graph {g+1}: Fidelity: {fidelity:.3f}')

    shd, err, acyc, runtime = [np.zeros((len(args_combs)))  for _ in range(4)]
    for i, args in enumerate(args_combs):
        args_aux = args.copy()
        args_aux['lamb'] = args_aux['lamb'] if fix_lamb else get_lamb_value(N, M, args['lamb'])
        model = model_const(**model_args)
        t_init = perf_counter()
        if isinstance(model, MetMulColide):
            W_est, _ = model.fit(X, **args_aux)
        else:
            W_est = model.fit(X, **args_aux)
        t_end = perf_counter()
    
        W_est_bin = utils.to_bin(W_est, thr)
        shd[i], _, _ = utils.count_accuracy(W_true_bin, W_est_bin)
        err[i] = utils.compute_norm_sq_err(W_true, W_est, norm_W_true)
        runtime[i] = t_end - t_init
        acyc[i] = model.dagness(W_est)

        if verb and g == 0:
            text = args2str(args)
            print(f'\t- {text}: shd {shd[i]}  -  err: {err[i]:.3f}  -  acyc: {acyc[i]:.5g}  -  time: {runtime[i]:.3f}')
    
    return shd, err, acyc, runtime

## Experiment parameters

In [ ]:
model_const = MetMulColide  # MetMulDagma

model_args = {
    'primal_opt': 'sca',  # 'adam', 'fista', 'pgd
    'acyclicity': 'logdet',
    'restart': True,  # Only used in FISTA
}

verb = True
thr = .2
n_dags = 30 if DATASET != "SACHS" else 1
std_x = False
fix_lamb = False
N = 100  
data_params = {
    'n_nodes': N,
    'n_samples': 500, # 1000,
    'graph_type': 'er',
    'edges': 4*N,
    'edge_type': 'positive',
    'w_range': (.5, 1),
    'var': 1, # 1/np.sqrt(N),
}

Hyperparams = {
    'stepsize': [1e-5, 5e-5, 1e-4, 3e-4], # 5e-5
    'alpha_0': [.01],
    'rho_0': [.05],
    'beta': [1.2, 2], # higher?
    's': [1],
    'lamb': [.1],
    'iters_in': [500, 1000, 5000, 10000, 20000], #[30000, 50000],
    'iters_out': [5, 10, 25, 50],
    'tol': [1e-6],
    'sca_adam': [True],
}

# Hyperparams = {
#     'stepsize': [5e-5], # 5e-5
#     'alpha_0': [.1],
#     'rho_0': [.05],
#     'beta': [2], # higher?
#     's': [1],
#     'lamb': [.1],
#     'iters_in': [20000], #[30000, 50000],
#     'iters_out': [10],
#     'tol': [1e-6],
#     'sca_adam': [True],
# }

if DATASET == "SACHS":
    N_CPUS = 1

print('CPUs employed:', N_CPUS)
print('Looking hyperparameters for dataset', DATASET)
# Get combination of hyperparams for grid search
args_combs = cartesian_product(Hyperparams)    

t_init = perf_counter()
results = Parallel(n_jobs=N_CPUS)(delayed(run_grid_search_tuning)
                  (g, data_params, args_combs, model_const, model_args, std_x, fix_lamb, thr, verb) for g in range(n_dags))
t_end = perf_counter()

shd, err, acyc, runtime = zip(*results)
metrics = {'shd': shd, 'err': err, 'acyc': acyc, 'time': runtime}

CPUs employed: 64
Looking hyperparameters for dataset SYNTH
Graph 1: Fidelity: 100.161
Graph 11: Fidelity: 100.009
Graph 2: Fidelity: 100.284
Graph 5: Fidelity: 99.723
Graph 9: Fidelity: 99.669
Graph 6: Fidelity: 100.394
Graph 23: Fidelity: 99.139
Graph 10: Fidelity: 99.881
Graph 25: Fidelity: 100.752
Graph 22: Fidelity: 99.123
Graph 8: Fidelity: 100.955
Graph 28: Fidelity: 100.270
Graph 12: Fidelity: 99.691
Graph 24: Fidelity: 99.260
Graph 7: Fidelity: 99.326
Graph 13: Fidelity: 99.781
Graph 14: Fidelity: 100.608
Graph 17: Fidelity: 99.816
Graph 3: Fidelity: 99.626
Graph 19: Fidelity: 98.432
Graph 15: Fidelity: 100.315
Graph 30: Fidelity: 100.232
Graph 27: Fidelity: 100.163
Graph 4: Fidelity: 99.734
Graph 16: Fidelity: 99.703
Graph 21: Fidelity: 100.056
Graph 26: Fidelity: 99.735
Graph 29: Fidelity: 99.440
Graph 18: Fidelity: 100.467
Graph 20: Fidelity: 98.821
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=500 ite=25 tol=1e-06 : shd 54.0  -  err: 0.133  -  acyc: 0.00068813  -  time: 11.193
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=500 ite=50 tol=1e-06 : shd 49.0  -  err: 0.113  -  acyc: 1.11e-05  -  time: 6.777
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=500 ite=100 tol=1e-06 : shd 31.0  -  err: 0.093  -  acyc: 8.351e-10  -  time: 5.552
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=1000 ite=25 tol=1e-06 : shd 19.0  -  err: 0.062  -  acyc: 0.013307  -  time: 5.205
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=1000 ite=50 tol=1e-06 : shd 8.0  -  err: 0.042  -  acyc: 7.2071e-07  -  time: 5.705
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=1000 ite=100 tol=1e-06 : shd 5.0  -  err: 0.037  -  acyc: -7.4385e-15  -  time: 6.641
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=5000 ite=25 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 0.0046483  -  time: 23.563
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=5000 ite=50 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 2.149e-07  -  time: 31.126
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=5000 ite=100 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 1.1535e-11  -  time: 32.984
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=10000 ite=25 tol=1e-06 : shd 1.0  -  err: 0.012  -  acyc: 0.00061099  -  time: 38.361
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=10000 ite=50 tol=1e-06 : shd 1.0  -  err: 0.012  -  acyc: 2.7548e-05  -  time: 42.236
	- ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0.1 ite=10000 ite=100 tol=1e-06 : shd 1.0  -  err: 0.012  -  acyc: 1.2588e-11  -  time: 45.118
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=500 ite=25 tol=1e-06 : shd 59.0  -  err: 0.149  -  acyc: 3.965e-05  -  time: 7.295
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=500 ite=50 tol=1e-06 : shd 55.0  -  err: 0.129  -  acyc: 1.0664e-07  -  time: 8.356
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=500 ite=100 tol=1e-06 : shd 421.0  -  err: 1.806  -  acyc: 0  -  time: 15.760
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=1000 ite=25 tol=1e-06 : shd 10.0  -  err: 0.050  -  acyc: 2.1978e-05  -  time: 8.779
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=1000 ite=50 tol=1e-06 : shd 7.0  -  err: 0.042  -  acyc: 4.2495e-08  -  time: 10.022
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=1000 ite=100 tol=1e-06 : shd 5.0  -  err: 0.036  -  acyc: 1.6653e-15  -  time: 10.944
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=5000 ite=25 tol=1e-06 : shd 1.0  -  err: 0.012  -  acyc: 0.00011268  -  time: 18.724
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=5000 ite=50 tol=1e-06 : shd 1.0  -  err: 0.012  -  acyc: 1.179e-11  -  time: 28.160
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=5000 ite=100 tol=1e-06 : shd 421.0  -  err: 1.728  -  acyc: 0  -  time: 40.825
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=10000 ite=25 tol=1e-06 : shd 1.0  -  err: 0.012  -  acyc: 0.00011346  -  time: 34.362
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=10000 ite=50 tol=1e-06 : shd 1.0  -  err: 0.012  -  acyc: 1.197e-11  -  time: 43.257
	- ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ite=10000 ite=100 tol=1e-06 : shd 420.0  -  err: 1.860  -  acyc: 2.6645e-15  -  time: 60.602
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=500 ite=25 tol=1e-06 : shd 66.0  -  err: 0.159  -  acyc: 0.0002698  -  time: 6.542
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=500 ite=50 tol=1e-06 : shd 59.0  -  err: 0.136  -  acyc: 5.6038e-07  -  time: 7.621
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=500 ite=100 tol=1e-06 : shd 420.0  -  err: 1.944  -  acyc: 3.3275e-05  -  time: 9.320
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=1000 ite=25 tol=1e-06 : shd 26.0  -  err: 0.072  -  acyc: 0.0015446  -  time: 6.120
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=1000 ite=50 tol=1e-06 : shd 16.0  -  err: 0.057  -  acyc: 1.2653e-05  -  time: 7.092
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=1000 ite=100 tol=1e-06 : shd 9.0  -  err: 0.042  -  acyc: -9.992e-16  -  time: 8.012
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=5000 ite=25 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 0.0002363  -  time: 15.821
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=5000 ite=50 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 4.0211e-06  -  time: 16.731
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=5000 ite=100 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 1.2476e-11  -  time: 16.565
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=10000 ite=25 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 0.00024626  -  time: 17.133
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=10000 ite=50 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 2.9576e-06  -  time: 21.692
	- ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0.1 ite=10000 ite=100 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 1.2512e-11  -  time: 19.700
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=500 ite=25 tol=1e-06 : shd 64.0  -  err: 0.150  -  acyc: 8.2406e-06  -  time: 4.505
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=500 ite=50 tol=1e-06 : shd 53.0  -  err: 0.131  -  acyc: 8.5042e-10  -  time: 5.663
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=500 ite=100 tol=1e-06 : shd 420.0  -  err: 1.804  -  acyc: 3.5527e-15  -  time: 14.604
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=1000 ite=25 tol=1e-06 : shd 25.0  -  err: 0.076  -  acyc: 0.00011309  -  time: 3.731
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=1000 ite=50 tol=1e-06 : shd 13.0  -  err: 0.055  -  acyc: 4.0043e-08  -  time: 5.013
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=1000 ite=100 tol=1e-06 : shd 422.0  -  err: 1.740  -  acyc: 0  -  time: 8.988
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=5000 ite=25 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 9.1524e-05  -  time: 14.086
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=5000 ite=50 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 6.4618e-10  -  time: 21.207
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=5000 ite=100 tol=1e-06 : shd 429.0  -  err: 1.762  -  acyc: 0  -  time: 26.666
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=10000 ite=25 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 0.00012401  -  time: 27.472
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=10000 ite=50 tol=1e-06 : shd 0.0  -  err: 0.009  -  acyc: 1.2286e-11  -  time: 37.323
	- ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ite=10000 ite=100 tol=1e-06 : shd 425.0  -  err: 1.957  -  acyc: 3.3307e-16  -  time: 37.440

In [4]:
print_best('shd', metrics, args_combs)
print_best('err', metrics, args_combs, all_best=True)
print()
print_best('shd', metrics, args_combs, agg_funct='median')
print_best('err', metrics, args_combs, agg_funct='median', all_best=True)

NameError: name 'metrics' is not defined

In [11]:
leg = [args2str(args) for args in args_combs]
utils.display_results(leg, metrics, agg='mean', file_name=f'{PATH}tuning_mean')
utils.display_results(leg, metrics, agg='median', file_name=f'{PATH}tuning_med')

,leg,shd,err,acyc,time
0,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,97.2667 ± 74.4907,0.2282 ± 0.1943,0.0011 ± 0.0013,7.4856 ± 3.5356
1,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,89.9667 ± 78.0463,0.2161 ± 0.2002,0.0000 ± 0.0000,6.6711 ± 2.5409
2,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,181.4333 ± 156.4195,0.6683 ± 0.7326,0.0000 ± 0.0000,6.6427 ± 3.0740
3,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,51.0333 ± 57.3605,0.1130 ± 0.1039,0.0020 ± 0.0035,4.8411 ± 1.6013
4,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,44.1000 ± 53.4680,0.1014 ± 0.0981,0.0000 ± 0.0000,6.0283 ± 2.6535
5,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,95.2333 ± 134.1975,0.3262 ± 0.5746,0.0000 ± 0.0000,8.1797 ± 4.4422
6,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.3000 ± 0.5859,0.0116 ± 0.0035,0.0021 ± 0.0019,19.9190 ± 4.6040
7,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.2667 ± 0.5735,0.0112 ± 0.0019,0.0000 ± 0.0000,25.9731 ± 4.0728
8,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,82.7333 ± 165.0531,0.3647 ± 0.7079,0.0000 ± 0.0000,29.8041 ± 5.8817
9,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.6000 ± 1.3808,0.0119 ± 0.0035,0.0020 ± 0.0022,39.5371 ± 7.2943
10,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.6000 ± 1.3808,0.0120 ± 0.0035,0.0000 ± 0.0000,43.6947 ± 5.5804
11,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,133.1333 ± 187.6422,0.5458 ± 0.7709,0.0000 ± 0.0000,49.9361 ± 8.9879
12,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,103.0667 ± 74.9800,0.2363 ± 0.1644,0.0001 ± 0.0001,6.5345 ± 2.3893
13,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,94.8333 ± 78.7892,0.2217 ± 0.1697,0.0000 ± 0.0000,7.4844 ± 2.9729
14,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,263.4000 ± 142.5343,1.0443 ± 0.7820,-0.0000 ± 0.0000,10.2758 ± 6.2441
15,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,45.0333 ± 52.4541,0.1025 ± 0.0957,0.0001 ± 0.0002,6.9728 ± 2.1075
16,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,39.1000 ± 51.9932,0.0915 ± 0.0950,0.0000 ± 0.0000,8.1238 ± 2.6620
17,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,235.8333 ± 170.7579,0.9679 ± 0.8295,0.0000 ± 0.0000,11.3513 ± 5.7522
18,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,0.8667 ± 1.1470,0.0129 ± 0.0037,0.0000 ± 0.0000,17.7584 ± 4.8870
19,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,0.8667 ± 1.1470,0.0129 ± 0.0037,0.0000 ± 0.0000,21.4162 ± 6.6303
20,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,295.3667 ± 177.5854,1.3398 ± 0.8058,0.0000 ± 0.0000,28.4953 ± 11.0178
21,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,1.5000 ± 1.7272,0.0149 ± 0.0054,0.0001 ± 0.0002,27.6752 ± 8.7472
22,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,1.5000 ± 1.7272,0.0148 ± 0.0055,0.0000 ± 0.0000,31.5323 ± 11.0814
23,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,268.8000 ± 189.2961,1.1714 ± 0.8384,-0.0000 ± 0.0000,41.2167 ± 19.7511
24,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,94.8667 ± 78.4622,0.2094 ± 0.1716,0.0006 ± 0.0005,6.2136 ± 1.6826
25,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,84.3000 ± 80.3651,0.1906 ± 0.1737,0.0000 ± 0.0000,7.0399 ± 1.9377
26,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,210.3000 ± 165.2340,0.7899 ± 0.7625,0.0000 ± 0.0000,9.1077 ± 3.5144
27,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,53.1667 ± 74.4612,0.1245 ± 0.1719,0.0011 ± 0.0013,5.4762 ± 1.2788
28,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,44.8333 ± 76.9039,0.1106 ± 0.1760,0.0000 ± 0.0000,6.2948 ± 1.5815
29,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,156.8333 ± 177.1867,0.6303 ± 0.7918,0.0000 ± 0.0000,8.3353 ± 2.4628
30,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,10.6667 ± 55.2264,0.0309 ± 0.1070,0.0003 ± 0.0002,13.0998 ± 3.3742
31,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,10.6667 ± 55.2264,0.0309 ± 0.1070,0.0000 ± 0.0000,15.8812 ± 4.8437
32,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,144.4667 ± 189.8734,0.5879 ± 0.7881,0.0000 ± 0.0000,19.0415 ± 7.5526
33,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,7.5333 ± 40.0131,0.0213 ± 0.0577,0.0002 ± 0.0002,21.9695 ± 6.5769
34,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,7.5333 ± 40.0131,0.0214 ± 0.0577,0.0000 ± 0.0000,24.1845 ± 7.2557
35,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,141.2000 ± 188.4607,0.5357 ± 0.7314,0.0000 ± 0.0000,27.7585 ± 11.3833
36,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,98.8333 ± 91.7359,0.2253 ± 0.2137,0.0000 ± 0.0000,5.3686 ± 1.7992
37,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,88.5000 ± 94.7290,0.2080 ± 0.2172,0.0000 ± 0.0000,6.1732 ± 2.1367
38,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,329.5333 ± 133.4610,1.3880 ± 0.6975,0.0011 ± 0.0057,10.0290 ± 5.7872
39,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,46.5667 ± 61.8324,0.1100 ± 0.1221,0.0001 ± 0.0002,4.4225 ± 1.5810
40,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,36.3667 ± 61.3664,0.0906 ± 0.1205,0.0000 ± 0.0000,5.6029 ± 1.9718
41,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,341.4333 ± 129.1569,1.5184 ± 0.6692,-0.0000 ± 0.0000,9.9105 ± 5.1383
42,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,11.7667 ± 61.3268,0.0337 ± 0.1214,0.0001 ± 0.0000,11.0641 ± 3.9956
43,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,25.2333 ± 93.2912,0.0955 ± 0.3497,0.0000 ± 0.0000,14.0856 ± 5.6890
44,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,306.5667 ± 169.2242,1.3579 ± 0.7743,-0.0000 ± 0.0000,17.9648 ± 8.2260
45,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,1.2000 ± 5.7353,0.0125 ± 0.0083,0.0001 ± 0.0000,18.5441 ± 7.4678
46,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,13.9333 ± 71.9147,0.0699 ± 0.3138,0.0000 ± 0.0000,23.1409 ± 11.1600
47,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,254.4667 ± 193.8874,1.1350 ± 0.8648,0.0000 ± 0.0000,32.1132 ± 17.3272

DataFrame saved to ./results/tuning/tuning_mean.csv

,leg,shd,err,acyc,time
0,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,60.0000 ± 74.4907,0.1267 ± 0.1943,0.0005 ± 0.0013,7.1879 ± 3.5356
1,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,48.5000 ± 78.0463,0.1131 ± 0.2002,0.0000 ± 0.0000,6.7499 ± 2.5409
2,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,150.0000 ± 156.4195,0.3545 ± 0.7326,0.0000 ± 0.0000,6.6226 ± 3.0740
3,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,22.0000 ± 57.3605,0.0609 ± 0.1039,0.0007 ± 0.0035,4.9287 ± 1.6013
4,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,13.5000 ± 53.4680,0.0427 ± 0.0981,0.0000 ± 0.0000,5.6524 ± 2.6535
5,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,64.5000 ± 134.1975,0.1428 ± 0.5746,0.0000 ± 0.0000,6.6489 ± 4.4422
6,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.0000 ± 0.5859,0.0108 ± 0.0035,0.0021 ± 0.0019,20.1009 ± 4.6040
7,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.0000 ± 0.5735,0.0108 ± 0.0019,0.0000 ± 0.0000,26.7347 ± 4.0728
8,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.0000 ± 165.0531,0.0117 ± 0.7079,0.0000 ± 0.0000,29.5927 ± 5.8817
9,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.0000 ± 1.3808,0.0106 ± 0.0035,0.0018 ± 0.0022,39.7444 ± 7.2943
10,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.0000 ± 1.3808,0.0106 ± 0.0035,0.0000 ± 0.0000,42.0539 ± 5.5804
11,ste=1e-05 alp=0.01 rho=0.01 bet=1.5 s=1 lam=0....,0.0000 ± 187.6422,0.0127 ± 0.7709,0.0000 ± 0.0000,48.8868 ± 8.9879
12,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,59.0000 ± 74.9800,0.1289 ± 0.1644,0.0000 ± 0.0001,6.7971 ± 2.3893
13,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,48.5000 ± 78.7892,0.1100 ± 0.1697,0.0000 ± 0.0000,8.0627 ± 2.9729
14,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,256.5000 ± 142.5343,0.5506 ± 0.7820,0.0000 ± 0.0000,9.7372 ± 6.2441
15,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,19.0000 ± 52.4541,0.0523 ± 0.0957,0.0000 ± 0.0002,6.3804 ± 2.1075
16,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,9.5000 ± 51.9932,0.0400 ± 0.0950,0.0000 ± 0.0000,8.2206 ± 2.6620
17,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,309.5000 ± 170.7579,0.9545 ± 0.8295,0.0000 ± 0.0000,11.2938 ± 5.7522
18,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,0.0000 ± 1.1470,0.0108 ± 0.0037,0.0000 ± 0.0000,18.8101 ± 4.8870
19,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,0.0000 ± 1.1470,0.0108 ± 0.0037,0.0000 ± 0.0000,23.6389 ± 6.6303
20,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,398.0000 ± 177.5854,1.8007 ± 0.8058,0.0000 ± 0.0000,30.2713 ± 11.0178
21,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,1.0000 ± 1.7272,0.0124 ± 0.0054,0.0000 ± 0.0002,29.5403 ± 8.7472
22,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,1.0000 ± 1.7272,0.0120 ± 0.0055,0.0000 ± 0.0000,33.7673 ± 11.0814
23,ste=1e-05 alp=0.01 rho=0.01 bet=2 s=1 lam=0.1 ...,386.0000 ± 189.2961,1.7558 ± 0.8384,0.0000 ± 0.0000,42.3913 ± 19.7511
24,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,63.5000 ± 78.4622,0.1355 ± 0.1716,0.0005 ± 0.0005,6.4451 ± 1.6826
25,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,50.5000 ± 80.3651,0.1149 ± 0.1737,0.0000 ± 0.0000,7.2726 ± 1.9377
26,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,192.5000 ± 165.2340,0.4640 ± 0.7625,0.0000 ± 0.0000,9.2388 ± 3.5144
27,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,26.0000 ± 74.4612,0.0684 ± 0.1719,0.0005 ± 0.0013,5.5160 ± 1.2788
28,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,17.0000 ± 76.9039,0.0496 ± 0.1760,0.0000 ± 0.0000,6.3393 ± 1.5815
29,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,48.0000 ± 177.1867,0.1044 ± 0.7918,0.0000 ± 0.0000,8.3888 ± 2.4628
30,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,0.0000 ± 55.2264,0.0105 ± 0.1070,0.0002 ± 0.0002,13.3728 ± 3.3742
31,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,0.0000 ± 55.2264,0.0105 ± 0.1070,0.0000 ± 0.0000,16.6141 ± 4.8437
32,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,0.5000 ± 189.8734,0.0130 ± 0.7881,0.0000 ± 0.0000,18.3515 ± 7.5526
33,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,0.0000 ± 40.0131,0.0103 ± 0.0577,0.0002 ± 0.0002,21.7054 ± 6.5769
34,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,0.0000 ± 40.0131,0.0103 ± 0.0577,0.0000 ± 0.0000,24.9938 ± 7.2557
35,ste=1e-05 alp=0.01 rho=0.05 bet=1.5 s=1 lam=0....,0.0000 ± 188.4607,0.0113 ± 0.7314,0.0000 ± 0.0000,26.7415 ± 11.3833
36,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,59.5000 ± 91.7359,0.1322 ± 0.2137,0.0000 ± 0.0000,5.6646 ± 1.7992
37,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,46.5000 ± 94.7290,0.1118 ± 0.2172,0.0000 ± 0.0000,6.3270 ± 2.1367
38,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,398.0000 ± 133.4610,1.8009 ± 0.6975,0.0000 ± 0.0057,8.3765 ± 5.7872
39,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,24.0000 ± 61.8324,0.0610 ± 0.1221,0.0001 ± 0.0002,4.1086 ± 1.5810
40,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,13.0000 ± 61.3664,0.0430 ± 0.1205,0.0000 ± 0.0000,5.3819 ± 1.9718
41,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,401.5000 ± 129.1569,1.8096 ± 0.6692,0.0000 ± 0.0000,8.9439 ± 5.1383
42,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,0.0000 ± 61.3268,0.0106 ± 0.1214,0.0000 ± 0.0000,10.2180 ± 3.9956
43,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,0.0000 ± 93.2912,0.0107 ± 0.3497,0.0000 ± 0.0000,13.7207 ± 5.6890
44,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,399.5000 ± 169.2242,1.7730 ± 0.7743,0.0000 ± 0.0000,16.1767 ± 8.2260
45,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,0.0000 ± 5.7353,0.0105 ± 0.0083,0.0001 ± 0.0000,17.0955 ± 7.4678
46,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,0.0000 ± 71.9147,0.0105 ± 0.3138,0.0000 ± 0.0000,21.2921 ± 11.1600
47,ste=1e-05 alp=0.01 rho=0.05 bet=2 s=1 lam=0.1 ...,389.5000 ± 193.8874,1.7231 ± 0.8648,0.0000 ± 0.0000,32.5369 ± 17.3272

DataFrame saved to ./results/tuning/tuning_med.csv

In [ ]:
# ### Load and plot data
# import pandas as pd
# pd.set_option("display.max_colwidth", None)

# df_mean = pd.read_csv(PATH + "tuning_mean.csv")
# df_med = pd.read_csv(PATH + "tuning_med.csv")


# df_mean["err_num"] = (
#     df_mean["err"]
#       .str.extract(r"([0-9]+\.?[0-9]*)")[0]
#       .astype(float)
# )
# print("Args with min mean err:")
# print(df_mean.loc[df_mean["err_num"].idxmin()])
# print()

# df_med["err_num"] = (
#     df_med["err"]
#       .str.extract(r"([0-9]+\.?[0-9]*)")[0]
#       .astype(float)
# )
# print("Args with min median err:")
# print(df_med.loc[df_med["err_num"].idxmin()])

Args with min mean err:
leg        ste=5e-06 alp=0.01 rho=5 bet=2 s=1 lam=0.01 ite=500 ite=10 tol=1e-06
shd                                                            17.0000  ± 0.0000
err                                                             0.8243  ± 0.0000
acyc                                                            0.0000  ± 0.0000
time                                                            0.4262  ± 0.0000
err_num                                                                   0.8243
Name: 408, dtype: object

Args with min median err:
leg        ste=5e-06 alp=0.01 rho=5 bet=2 s=1 lam=0.01 ite=500 ite=10 tol=1e-06
shd                                                            17.0000  ± 0.0000
err                                                             0.8243  ± 0.0000
acyc                                                            0.0000  ± 0.0000
time                                                            0.4262  ± 0.0000
err_num                                                                   0.8243
Name: 408, dtype: object